# Bluetooth なシリアルポートへの接続

なんか色々ハマりました。

- ペアリングできない
- 接続できない
- ローカルにあるプロジェクトを import
- デバイスが開けない
- デバイスが busy

以下に控えを。

<!-- more -->

ペアリングできない
---------------------

PIN がわからなかったのですが "1234" で良かった模様。ペアリングはできました。がしかし接続ができない。

接続できない
---------------------

`blueman` というパケジを導入して `bluetooth-manager` というコマンドで GUI を起動して serial な接続を確立することができました。がしかし、Python から接続できず。

ローカルにあるプロジェクトを import
---------------------

というか、それ以前に import ができていない。

色々確認してみるに `git clone` したディレクトリをカレントディレクトリにしておけば

```
>>> import obd
```

でそのモジュールが import できる模様。成程。

デバイスが開けない
---------------------

ということで import はできたのですが接続はまだ成功しない。とりあえず `__init__.py` にてログレベルを設定していたので `DEBUG` にして

```
logger.setLevel(logging.DEBUG)
```

確認してみるに権限が無いとのこと。`/etc/udev/rules.d/50-udev-default.rules` を新規に作成して以下を追加。

```
KERNEL=="tty[A-Z]*[0-9]|pppox[0-9]*|ircomm[0-9]*|noz[0-9]*|rfcomm[0-9]*", GROUP="dialout", MODE="0666"
```

デバイスが busy
---------------------

どうも root だと cat できます。ルールを以下にしてみましたがまだ駄目。

```
KERNEL=="tty[A-Z]*[0-9]|pppox[0-9]*|ircomm[0-9]*|noz[0-9]*|rfcomm[0-9]*", OWNER="rms", GROUP="dialout", MODE="0666"
```

どうやら ModemManager が悪さしてるらしい、という情報があり止めてみるなど。

```
$ sudo systemctl stop ModemManager.service
```

これで何とかなったか、と思いきや、デバイス自体が不良なのか未だ接続できておらずで、業者確認および違うデバイス発注かな、と思っている次第す。
